"""Stage host-wide agent instructions for read-only container mounts.

The host source is copied per agent and file name to a host-level staging
directory, under that agent's expected filename. Directory mounts let atomic replacements
reach existing containers without exposing the host config tree.
"""

from __future__ import annotations

import os
import posixpath
import tempfile
from pathlib import Path
from typing import TYPE_CHECKING

from jailbee.config import CONTAINER_USERNAME, device_name
from jailbee.paths import display_path, xdg_data_home
from jailbee.tui import warn_plain

if TYPE_CHECKING:
    from jailbee.config import Config
    from jailbee.config.models_agents import AgentGlobalInstructions

MARKER_TEMPLATE = "<!-- generated by jailbee from {source} — edit that file on the host -->"


def source_path() -> Path:
    """Return the optional host-wide AGENTS.md beside global.yaml."""
    # global_config imports Config; keep it lazy to avoid a module cycle.
    from jailbee.global_config import default_global_config_path

    return default_global_config_path().parent / "AGENTS.md"


def staging_root() -> Path:
    """Return the host-level root for staged agent instructions."""
    return xdg_data_home() / "jailbee" / "agent-instructions"


def staging_dir(agent: str, filename: str) -> Path:
    """Return the host-level staging directory holding one agent's one file.

    One directory per (agent, file name), and that directory is what a
    container mounts. A repo that configures an unusual `global_instructions.file`
    therefore only ever puts that file into its own containers, never into those
    of another repo that mounts a different file name for the same agent.
    """
    return staging_root() / agent / "by-file" / filename


def instruction_agents(cfg: Config) -> list[tuple[str, AgentGlobalInstructions]]:
    """Enabled agents wired for host-wide instructions, unless opted out."""
    if not cfg.agent_instructions_enabled():
        return []
    return [
        (name, agent.global_instructions)
        for name, agent in sorted(cfg.agents.items())
        if agent.enabled and agent.global_instructions is not None
    ]


def desired_content(source: Path) -> bytes | None:
    """Return the marked source bytes, or None if the source is absent."""
    try:
        content = source.read_bytes()
    except FileNotFoundError:
        return None
    marker = MARKER_TEMPLATE.format(source=display_path(source)).encode()
    return marker + b"\n" + content


def _write_atomically(target: Path, content: bytes) -> None:
    fd, tmp = tempfile.mkstemp(dir=target.parent, prefix=f".{target.name}.")
    try:
        with os.fdopen(fd, "wb") as fh:
            fh.write(content)
        os.chmod(tmp, 0o644)
        os.replace(tmp, target)
    except BaseException:
        Path(tmp).unlink(missing_ok=True)
        raise


def sync_global_instructions(cfg: Config) -> None:
    """Sync staged copies without letting a best-effort host copy fail a command."""
    agents = instruction_agents(cfg)
    if not agents:
        return

    source = source_path()
    try:
        content = desired_content(source)
    except OSError as exc:
        warn_plain(
            f"cannot read {display_path(source)}: {exc} — keeping the previous copy", stderr=True
        )
        content_known = False
        content = None
    else:
        content_known = True

    for name, gi in agents:
        directory = staging_dir(name, gi.file)
        target = directory / gi.file
        try:
            directory.mkdir(parents=True, exist_ok=True)
            if not content_known:
                continue
            if content is None:
                target.unlink(missing_ok=True)
                continue
            try:
                current = target.read_bytes()
            except FileNotFoundError:
                current = None
            if current != content:
                _write_atomically(target, content)
        except OSError as exc:
            warn_plain(
                f"cannot update agent instructions for {name} in {directory}: {exc}",
                stderr=True,
            )


def missing_staging_dirs(cfg: Config) -> list[Path]:
    """Return configured agent staging directories that do not yet exist."""
    return [
        directory
        for name, gi in instruction_agents(cfg)
        if not (directory := staging_dir(name, gi.file)).is_dir()
    ]


def profile_devices(cfg: Config) -> dict[str, dict[str, str]]:
    """Build read-only disk devices for agents wired to host-wide instructions."""
    home = f"/home/{CONTAINER_USERNAME}"
    devices: dict[str, dict[str, str]] = {}
    for name, gi in instruction_agents(cfg):
        path = gi.dir.replace("~", home, 1) if gi.dir.startswith("~") else gi.dir
        devices[f"agent-instructions-{device_name(name)}"] = {
            "type": "disk",
            "source": str(staging_dir(name, gi.file)),
            "path": path,
            "readonly": "true",
        }
    _validate_mount_destinations(cfg, devices)
    return devices


def _container_path_parts(path: str) -> tuple[str, ...]:
    home = f"/home/{CONTAINER_USERNAME}"
    if path == "~":
        path = home
    elif path.startswith("~/"):
        path = f"{home}/{path[2:]}"
    return Path(posixpath.normpath("/" + path.lstrip("/"))).parts


def _validate_mount_destinations(cfg: Config, devices: dict[str, dict[str, str]]) -> None:
    from jailbee.config import ConfigError

    mounts = [
        (f"host mount {mount.host}", mount.container) for mount in cfg.effective_host_mounts()
    ]
    mounts.extend(
        (f"shared-{cache.name}", cache.container_path) for cache in cfg.effective_shared_caches()
    )
    for name, device in devices.items():
        target = _container_path_parts(device["path"])
        for mount_name, mount_path in mounts:
            other = _container_path_parts(mount_path)
            if target[: len(other)] == other or other[: len(target)] == target:
                raise ConfigError(
                    f"{name} at {device['path']!r} overlaps {mount_name} at {mount_path!r}; "
                    "set agent_instructions: false in global.yaml or remap the conflicting "
                    "mount/global_instructions.dir to disjoint destinations"
                )
        mounts.append((name, device["path"]))
