"""Stage host-wide agent instructions for read-only container mounts.

The host source is copied per agent to a host-level staging directory, under
that agent's expected filename. Directory mounts let atomic replacements
reach existing containers without exposing the host config tree.
"""

from __future__ import annotations

import os
import tempfile
from pathlib import Path
from typing import TYPE_CHECKING

from jailbee.config import CONTAINER_USERNAME, device_name
from jailbee.paths import display_path, xdg_data_home
from jailbee.tui import warn_plain

if TYPE_CHECKING:
    from jailbee.config import Config
    from jailbee.config.models_agents import AgentGlobalInstructions

MARKER_TEMPLATE = "<!-- generated by jailbee from {source} — edit that file on the host -->"


def source_path() -> Path:
    """Return the optional host-wide AGENTS.md beside global.yaml."""
    # global_config imports Config; keep it lazy to avoid a module cycle.
    from jailbee.global_config import default_global_config_path

    return default_global_config_path().parent / "AGENTS.md"


def staging_root() -> Path:
    """Return the host-level root for staged agent instructions."""
    return xdg_data_home() / "jailbee" / "agent-instructions"


def staging_dir(agent: str) -> Path:
    """Return one agent's host-level instruction staging directory."""
    return staging_root() / agent


def instruction_agents(cfg: Config) -> list[tuple[str, AgentGlobalInstructions]]:
    """Enabled agents wired for host-wide instructions, unless opted out."""
    if not cfg.agent_instructions_enabled():
        return []
    return [
        (name, agent.global_instructions)
        for name, agent in sorted(cfg.agents.items())
        if agent.enabled and agent.global_instructions is not None
    ]


def desired_content(source: Path) -> bytes | None:
    """Return the marked source bytes, or None if the source is absent."""
    try:
        content = source.read_bytes()
    except FileNotFoundError:
        return None
    marker = MARKER_TEMPLATE.format(source=display_path(source)).encode()
    return marker + b"\n" + content


def _write_atomically(target: Path, content: bytes) -> None:
    fd, tmp = tempfile.mkstemp(dir=target.parent, prefix=f".{target.name}.")
    try:
        with os.fdopen(fd, "wb") as fh:
            fh.write(content)
        os.chmod(tmp, 0o644)
        os.replace(tmp, target)
    except BaseException:
        Path(tmp).unlink(missing_ok=True)
        raise


def sync_global_instructions(cfg: Config) -> None:
    """Sync staged copies without letting a best-effort host copy fail a command."""
    agents = instruction_agents(cfg)
    if not agents:
        return

    source = source_path()
    try:
        content = desired_content(source)
    except OSError as exc:
        warn_plain(
            f"cannot read {display_path(source)}: {exc} — keeping the previous copy", stderr=True
        )
        content_known = False
        content = None
    else:
        content_known = True

    for name, gi in agents:
        target = staging_dir(name) / gi.file
        try:
            target.parent.mkdir(parents=True, exist_ok=True)
            if not content_known:
                continue
            if content is None:
                target.unlink(missing_ok=True)
                continue
            try:
                current = target.read_bytes()
            except FileNotFoundError:
                current = None
            if current != content:
                _write_atomically(target, content)
        except OSError as exc:
            warn_plain(
                f"cannot update agent instructions for {name} in {target.parent}: {exc}",
                stderr=True,
            )


def missing_staging_dirs(cfg: Config) -> list[Path]:
    """Return configured agent staging directories that do not yet exist."""
    return [
        staging_dir(name) for name, _ in instruction_agents(cfg) if not staging_dir(name).is_dir()
    ]


def profile_devices(cfg: Config) -> dict[str, dict[str, str]]:
    """Build read-only disk devices for agents wired to host-wide instructions."""
    home = f"/home/{CONTAINER_USERNAME}"
    devices: dict[str, dict[str, str]] = {}
    for name, gi in instruction_agents(cfg):
        path = gi.dir.replace("~", home, 1) if gi.dir.startswith("~") else gi.dir
        devices[f"agent-instructions-{device_name(name)}"] = {
            "type": "disk",
            "source": str(staging_dir(name)),
            "path": path,
            "readonly": "true",
        }
    return devices
