"""Stage host-wide agent instructions for read-only container mounts.

The host source is copied per agent to a host-level staging directory, under
that agent's expected filename. Directory mounts let atomic replacements
reach existing containers without exposing the host config tree.
"""

from __future__ import annotations

import fcntl
import json
import os
import posixpath
import tempfile
from pathlib import Path
from typing import TYPE_CHECKING

from jailbee.config import CONTAINER_USERNAME, device_name
from jailbee.paths import display_path, xdg_data_home
from jailbee.tui import warn_plain

if TYPE_CHECKING:
    from jailbee.config import Config
    from jailbee.config.models_agents import AgentGlobalInstructions

MARKER_TEMPLATE = "<!-- generated by jailbee from {source} — edit that file on the host -->"


def source_path() -> Path:
    """Return the optional host-wide AGENTS.md beside global.yaml."""
    # global_config imports Config; keep it lazy to avoid a module cycle.
    from jailbee.global_config import default_global_config_path

    return default_global_config_path().parent / "AGENTS.md"


def staging_root() -> Path:
    """Return the host-level root for staged agent instructions."""
    return xdg_data_home() / "jailbee" / "agent-instructions"


def staging_dir(agent: str) -> Path:
    """Return one agent's host-level instruction staging directory."""
    return staging_root() / agent


def instruction_agents(cfg: Config) -> list[tuple[str, AgentGlobalInstructions]]:
    """Enabled agents wired for host-wide instructions, unless opted out."""
    if not cfg.agent_instructions_enabled():
        return []
    return [
        (name, agent.global_instructions)
        for name, agent in sorted(cfg.agents.items())
        if agent.enabled and agent.global_instructions is not None
    ]


def desired_content(source: Path) -> bytes | None:
    """Return the marked source bytes, or None if the source is absent."""
    try:
        content = source.read_bytes()
    except FileNotFoundError:
        return None
    marker = MARKER_TEMPLATE.format(source=display_path(source)).encode()
    return marker + b"\n" + content


def _write_atomically(target: Path, content: bytes) -> None:
    fd, tmp = tempfile.mkstemp(dir=target.parent, prefix=f".{target.name}.")
    try:
        with os.fdopen(fd, "wb") as fh:
            fh.write(content)
        os.chmod(tmp, 0o644)
        os.replace(tmp, target)
    except BaseException:
        Path(tmp).unlink(missing_ok=True)
        raise


def sync_global_instructions(cfg: Config) -> None:
    """Sync staged copies without letting a best-effort host copy fail a command."""
    agents = instruction_agents(cfg)
    if not agents:
        return

    source = source_path()
    try:
        content = desired_content(source)
    except OSError as exc:
        warn_plain(
            f"cannot read {display_path(source)}: {exc} — keeping the previous copy", stderr=True
        )
        content_known = False
        content = None
    else:
        content_known = True

    for name, gi in agents:
        target = staging_dir(name) / gi.file
        try:
            target.parent.mkdir(parents=True, exist_ok=True)
            if not content_known:
                continue
            # Keep metadata and its stable lock inode outside the mounted directory.
            registry = staging_root().parent / "agent-instructions-ownership" / f"{name}.json"
            registry.parent.mkdir(parents=True, exist_ok=True)
            with registry.with_suffix(".lock").open("a") as lock:
                fcntl.flock(lock, fcntl.LOCK_EX)
                try:
                    owned_names = _read_ownership(registry)
                    owned_names.add(gi.file)
                    _adopt_marked_copies(target.parent, source, owned_names)
                    # Persist before creating copies, including when the source
                    # is absent, so failed writes never leave unrecorded copies.
                    recorded = (json.dumps(sorted(owned_names)) + "\n").encode()
                    _write_atomically(registry, recorded)
                    for filename in sorted(owned_names):
                        owned = target.parent / filename
                        try:
                            if content is None:
                                owned.unlink(missing_ok=True)
                                continue
                            try:
                                current = owned.read_bytes()
                            except FileNotFoundError:
                                current = None
                            if current != content:
                                _write_atomically(owned, content)
                        except OSError as exc:
                            warn_plain(f"cannot update agent instructions at {owned}: {exc}", stderr=True)
                finally:
                    fcntl.flock(lock, fcntl.LOCK_UN)
        except OSError as exc:
            warn_plain(
                f"cannot update agent instructions for {name} in {target.parent}: {exc}",
                stderr=True,
            )


def _read_ownership(registry: Path) -> set[str]:
    try:
        records = json.loads(registry.read_bytes())
    except FileNotFoundError:
        return set()
    except (ValueError, UnicodeError) as exc:
        raise OSError(f"invalid ownership registry {registry}: {exc}") from exc
    if not isinstance(records, list):
        raise OSError(f"invalid ownership registry {registry}: expected a list")
    names: set[str] = set()
    for filename in records:
        if (
            isinstance(filename, str)
            and filename not in {"", ".", ".."}
            and "/" not in filename
            and "\\" not in filename
            and "\x00" not in filename
        ):
            names.add(filename)
        else:
            warn_plain(f"invalid filename in ownership registry {registry}: {filename!r}", stderr=True)
    return names


def _adopt_marked_copies(directory: Path, source: Path, names: set[str]) -> None:
    """Adopt legacy marked files; markerless unknown files cannot be inferred."""
    marker = MARKER_TEMPLATE.format(source=display_path(source)).encode() + b"\n"
    try:
        siblings = list(directory.iterdir())
    except OSError as exc:
        warn_plain(f"cannot discover agent instructions in {directory}: {exc}", stderr=True)
        return
    for sibling in siblings:
        if sibling.name in names:
            continue
        try:
            if sibling.is_symlink() or not sibling.is_file():
                continue
            with sibling.open("rb") as fh:
                if fh.read(len(marker)) == marker:
                    names.add(sibling.name)
        except OSError as exc:
            warn_plain(f"cannot inspect agent instructions at {sibling}: {exc}", stderr=True)


def missing_staging_dirs(cfg: Config) -> list[Path]:
    """Return configured agent staging directories that do not yet exist."""
    return [
        staging_dir(name) for name, _ in instruction_agents(cfg) if not staging_dir(name).is_dir()
    ]


def profile_devices(cfg: Config) -> dict[str, dict[str, str]]:
    """Build read-only disk devices for agents wired to host-wide instructions."""
    home = f"/home/{CONTAINER_USERNAME}"
    devices: dict[str, dict[str, str]] = {}
    for name, gi in instruction_agents(cfg):
        path = gi.dir.replace("~", home, 1) if gi.dir.startswith("~") else gi.dir
        devices[f"agent-instructions-{device_name(name)}"] = {
            "type": "disk",
            "source": str(staging_dir(name)),
            "path": path,
            "readonly": "true",
        }
    _validate_mount_destinations(cfg, devices)
    return devices


def _container_path_parts(path: str) -> tuple[str, ...]:
    home = f"/home/{CONTAINER_USERNAME}"
    if path == "~":
        path = home
    elif path.startswith("~/"):
        path = f"{home}/{path[2:]}"
    return Path(posixpath.normpath("/" + path.lstrip("/"))).parts


def _validate_mount_destinations(cfg: Config, devices: dict[str, dict[str, str]]) -> None:
    from jailbee.config import ConfigError

    mounts = [
        (f"host mount {mount.host}", mount.container) for mount in cfg.effective_host_mounts()
    ]
    mounts.extend(
        (f"shared-{cache.name}", cache.container_path) for cache in cfg.effective_shared_caches()
    )
    for name, device in devices.items():
        target = _container_path_parts(device["path"])
        for mount_name, mount_path in mounts:
            other = _container_path_parts(mount_path)
            if target[: len(other)] == other or other[: len(target)] == target:
                raise ConfigError(
                    f"{name} at {device['path']!r} overlaps {mount_name} at {mount_path!r}; "
                    "set agent_instructions: false in global.yaml or remap the conflicting "
                    "mount/global_instructions.dir to disjoint destinations"
                )
        mounts.append((name, device["path"]))
