from pathlib import Path

import pytest

from jailbee import agent_instructions as ai
from tests.conftest import with_agent


@pytest.fixture
def homes(tmp_path, monkeypatch):
    home = tmp_path / "home"
    home.mkdir()
    monkeypatch.setenv("HOME", str(home))
    cfg_home = tmp_path / "config"
    data_home = tmp_path / "data"
    monkeypatch.setenv("XDG_CONFIG_HOME", str(cfg_home))
    monkeypatch.setenv("XDG_DATA_HOME", str(data_home))
    (cfg_home / "jailbee").mkdir(parents=True)
    return cfg_home / "jailbee" / "AGENTS.md", data_home


@pytest.fixture
def claude_cfg(make_cfg, tmp_path):
    return make_cfg(tmp_path / "repo", agents={"claude": {"enabled": True}})


def staged(data_home: Path) -> Path:
    return data_home / "jailbee" / "agent-instructions" / "claude" / "CLAUDE.md"


def test_paths_follow_xdg(homes):
    source, data_home = homes
    assert ai.source_path() == source
    assert ai.staging_dir("claude") == data_home / "jailbee" / "agent-instructions" / "claude"


def test_instruction_agents_lists_enabled_claude(claude_cfg):
    [(name, gi)] = ai.instruction_agents(claude_cfg)
    assert (name, gi.dir, gi.file) == ("claude", "/etc/claude-code", "CLAUDE.md")


def test_instruction_agents_empty_when_opted_out(claude_cfg):
    claude_cfg._agent_instructions = False
    assert ai.instruction_agents(claude_cfg) == []


def test_instruction_agents_skips_disabled_agent(make_cfg, tmp_path):
    cfg = make_cfg(tmp_path / "repo", agents={"claude": {"enabled": False}})
    assert ai.instruction_agents(cfg) == []


def test_sync_copies_source_with_marker(homes, claude_cfg):
    source, data_home = homes
    source.write_bytes(b"Never use fable.\n")
    ai.sync_global_instructions(claude_cfg)
    content = staged(data_home).read_bytes()
    first, rest = content.split(b"\n", 1)
    assert first.decode() == (
        f"<!-- generated by jailbee from {source} — edit that file on the host -->"
    )
    assert rest == b"Never use fable.\n"


def test_sync_without_source_leaves_empty_dir(homes, claude_cfg):
    _, data_home = homes
    ai.sync_global_instructions(claude_cfg)
    assert staged(data_home).parent.is_dir()
    assert not staged(data_home).exists()


def test_sync_removes_staged_file_when_source_deleted(homes, claude_cfg):
    source, data_home = homes
    source.write_bytes(b"x")
    ai.sync_global_instructions(claude_cfg)
    source.unlink()
    ai.sync_global_instructions(claude_cfg)
    assert not staged(data_home).exists()
    assert staged(data_home).parent.is_dir()


def test_unchanged_content_is_not_rewritten(homes, claude_cfg):
    source, data_home = homes
    source.write_bytes(b"x")
    ai.sync_global_instructions(claude_cfg)
    before = staged(data_home).stat()
    ai.sync_global_instructions(claude_cfg)
    after = staged(data_home).stat()
    assert (before.st_ino, before.st_mtime_ns) == (after.st_ino, after.st_mtime_ns)


def test_changed_content_is_replaced_atomically(homes, claude_cfg):
    source, data_home = homes
    source.write_bytes(b"old")
    ai.sync_global_instructions(claude_cfg)
    before_ino = staged(data_home).stat().st_ino
    source.write_bytes(b"new")
    ai.sync_global_instructions(claude_cfg)
    assert staged(data_home).read_bytes().endswith(b"\nnew")
    assert staged(data_home).stat().st_ino != before_ino
    assert [p.name for p in staged(data_home).parent.iterdir()] == ["CLAUDE.md"]


def test_symlinked_source_stages_the_target(homes, claude_cfg, tmp_path):
    source, data_home = homes
    target = tmp_path / "dotfiles" / "AGENTS.md"
    target.parent.mkdir()
    target.write_bytes(b"from dotfiles")
    source.symlink_to(target)
    ai.sync_global_instructions(claude_cfg)
    assert staged(data_home).read_bytes().endswith(b"\nfrom dotfiles")


def test_symlink_loop_warns_and_keeps_previous(homes, claude_cfg, capsys):
    source, data_home = homes
    source.write_bytes(b"good")
    ai.sync_global_instructions(claude_cfg)
    before = staged(data_home).read_bytes()
    source.unlink()
    source.symlink_to(source)
    ai.sync_global_instructions(claude_cfg)
    assert staged(data_home).read_bytes() == before
    output = capsys.readouterr()
    assert output.out == ""
    assert "cannot read" in output.err


def test_bytes_are_staged_verbatim(homes, claude_cfg):
    source, data_home = homes
    payload = b"line one\r\nlatin-1: \xe4\xf6\r\n\x00end"
    source.write_bytes(payload)
    ai.sync_global_instructions(claude_cfg)
    assert staged(data_home).read_bytes().split(b"\n", 1)[1] == payload


def test_hand_edited_staged_file_is_restored(homes, claude_cfg):
    source, data_home = homes
    source.write_bytes(b"policy")
    ai.sync_global_instructions(claude_cfg)
    staged(data_home).write_bytes(b"tampered")
    ai.sync_global_instructions(claude_cfg)
    assert staged(data_home).read_bytes().endswith(b"\npolicy")


def test_unreadable_source_warns_and_keeps_previous(homes, claude_cfg, capsys):
    source, data_home = homes
    source.write_bytes(b"good")
    ai.sync_global_instructions(claude_cfg)
    source.unlink()
    source.mkdir()
    ai.sync_global_instructions(claude_cfg)
    assert staged(data_home).read_bytes().endswith(b"\ngood")
    output = capsys.readouterr()
    assert output.out == ""
    assert "cannot read" in output.err


def test_disabled_agent_in_this_repo_leaves_host_staging_alone(homes, make_cfg, tmp_path):
    source, data_home = homes
    source.write_bytes(b"policy")
    enabled = make_cfg(tmp_path / "b", agents={"claude": {"enabled": True}})
    ai.sync_global_instructions(enabled)
    source.unlink()
    disabled = make_cfg(tmp_path / "a", agents={"claude": {"enabled": False}})
    ai.sync_global_instructions(disabled)
    assert staged(data_home).read_bytes().endswith(b"\npolicy")


def test_write_failure_warns_not_raises(homes, claude_cfg, mocker, capsys):
    source, _ = homes
    source.write_bytes(b"x")
    mocker.patch("jailbee.agent_instructions.os.replace", side_effect=OSError("disk [full]"))
    ai.sync_global_instructions(claude_cfg)
    output = capsys.readouterr()
    assert output.out == ""
    assert "disk [full]" in output.err


def test_opted_out_sync_touches_nothing(homes, claude_cfg):
    source, data_home = homes
    source.write_bytes(b"x")
    claude_cfg._agent_instructions = False
    ai.sync_global_instructions(claude_cfg)
    assert not (data_home / "jailbee" / "agent-instructions").exists()


def test_missing_staging_dirs(homes, claude_cfg):
    _, data_home = homes
    assert ai.missing_staging_dirs(claude_cfg) == [
        data_home / "jailbee" / "agent-instructions" / "claude"
    ]
    ai.sync_global_instructions(claude_cfg)
    assert ai.missing_staging_dirs(claude_cfg) == []


def test_profile_devices_shape(homes, claude_cfg):
    _, data_home = homes
    assert ai.profile_devices(claude_cfg) == {
        "agent-instructions-claude": {
            "type": "disk",
            "source": str(data_home / "jailbee" / "agent-instructions" / "claude"),
            "path": "/etc/claude-code",
            "readonly": "true",
        }
    }


def test_profile_devices_expand_tilde(homes, make_cfg, tmp_path):
    cfg = with_agent(
        make_cfg(tmp_path / "repo"),
        "other",
        enabled=True,
        command="other",
        global_instructions={"dir": "~/.other-policy", "file": "AGENTS.md"},
    )
    devices = ai.profile_devices(cfg)
    assert devices["agent-instructions-other"]["path"] == "/home/dev/.other-policy"


def test_profile_devices_empty_when_opted_out(homes, claude_cfg):
    claude_cfg._agent_instructions = False
    assert ai.profile_devices(claude_cfg) == {}


@pytest.mark.parametrize(
    "destination",
    [
        "/etc/claude-code",
        "/etc",
        "/etc/claude-code/managed-settings.json",
        "/etc//claude-code/../claude-code/",
    ],
)
def test_instruction_mount_rejects_overlapping_host_policy(claude_cfg, destination):
    from jailbee.config import ConfigError, HostMount
    from jailbee.profiles import binds_profile_yaml

    cfg = claude_cfg.model_copy(
        update={"host_mounts": [HostMount(host="/policy", container=destination)]}
    )
    with pytest.raises(ConfigError, match=r"host.*policy.*agent_instructions: false"):
        binds_profile_yaml(cfg)
    cfg._agent_instructions = False
    assert "agent-instructions-claude" not in binds_profile_yaml(cfg)


def test_instruction_mount_rejects_normalized_shared_overlap(claude_cfg):
    from jailbee.config import ConfigError, SharedCache

    cfg = with_agent(
        claude_cfg,
        "other",
        enabled=True,
        command="other",
        global_instructions={"dir": "~/.policy", "file": "AGENTS.md"},
    )
    cfg = cfg.model_copy(
        update={
            "shared_caches": [
                SharedCache(
                    name="policy-state",
                    host_subpath="policy",
                    container_path="/home/dev//.policy/state",
                )
            ]
        }
    )
    with pytest.raises(ConfigError, match="shared-policy-state"):
        ai.profile_devices(cfg)


def test_instruction_mount_rejects_other_instruction_overlap(claude_cfg):
    from jailbee.config import ConfigError

    cfg = with_agent(
        claude_cfg,
        "other",
        enabled=True,
        command="other",
        global_instructions={"dir": "/etc/claude-code/nested", "file": "AGENTS.md"},
    )
    with pytest.raises(ConfigError, match=r"agent-instructions-other.*agent-instructions-claude"):
        ai.profile_devices(cfg)


def test_instruction_mount_accepts_segment_distinct_policy(claude_cfg):
    from jailbee.config import HostMount

    cfg = claude_cfg.model_copy(
        update={"host_mounts": [HostMount(host="/policy", container="/etc/claude-code-other")]}
    )
    assert "agent-instructions-claude" in ai.profile_devices(cfg)


@pytest.mark.parametrize("remove", [False, True])
def test_sync_refreshes_all_same_agent_repo_filenames(homes, claude_cfg, remove):
    source, data_home = homes
    other = with_agent(
        claude_cfg, "claude", global_instructions={"dir": "/etc/claude-code", "file": "OTHER.md"}
    )
    source.write_bytes(b"old")
    ai.sync_global_instructions(claude_cfg)
    ai.sync_global_instructions(other)
    if remove:
        source.unlink()
    else:
        source.write_bytes(b"new\r\n\xff")
    ai.sync_global_instructions(other)
    for target in (staged(data_home), staged(data_home).with_name("OTHER.md")):
        if remove:
            assert not target.exists()
        else:
            assert target.read_bytes().split(b"\n", 1)[1] == b"new\r\n\xff"


def test_filename_rename_refreshes_owned_copies_retains_unknown(homes, claude_cfg):
    source, data_home = homes
    source.write_bytes(b"old")
    ai.sync_global_instructions(claude_cfg)
    unknown = staged(data_home).with_name("managed-settings.json")
    unknown.write_bytes(b"unrelated")
    renamed = with_agent(
        claude_cfg, "claude", global_instructions={"dir": "/etc/claude-code", "file": "NEW.md"}
    )
    source.write_bytes(b"new")
    ai.sync_global_instructions(renamed)
    assert staged(data_home).read_bytes().endswith(b"\nnew")
    assert unknown.read_bytes() == b"unrelated"
    source.unlink()
    ai.sync_global_instructions(renamed)
    assert not staged(data_home).exists()
    assert not staged(data_home).with_name("NEW.md").exists()
    assert unknown.read_bytes() == b"unrelated"


@pytest.mark.parametrize("remove", [False, True])
@pytest.mark.parametrize("edited", [b"hand edited", b""])
def test_markerless_other_repo_copy_remains_owned(homes, claude_cfg, remove, edited):
    source, data_home = homes
    other = with_agent(
        claude_cfg, "claude", global_instructions={"dir": "/etc/claude-code", "file": "OTHER.md"}
    )
    source.write_bytes(b"old")
    ai.sync_global_instructions(claude_cfg)
    ai.sync_global_instructions(other)
    staged(data_home).write_bytes(edited)
    if remove:
        source.unlink()
    else:
        source.write_bytes(b"new")
    ai.sync_global_instructions(other)
    for target in (staged(data_home), staged(data_home).with_name("OTHER.md")):
        if remove:
            assert not target.exists()
        else:
            assert target.read_bytes().endswith(b"\nnew")


@pytest.mark.parametrize("remove", [False, True])
@pytest.mark.parametrize("owned", [False, True])
def test_sibling_failure_does_not_block_known_target(
    homes, claude_cfg, remove, owned, monkeypatch, capsys
):
    source, data_home = homes
    other = with_agent(
        claude_cfg, "claude", global_instructions={"dir": "/etc/claude-code", "file": "OTHER.md"}
    )
    source.write_bytes(b"old")
    ai.sync_global_instructions(claude_cfg)
    ai.sync_global_instructions(other)
    blocked = staged(data_home) if owned else staged(data_home).with_name("managed-settings.json")
    if not owned:
        blocked.write_bytes(b"unrelated")
    method = "unlink" if owned and remove else "open"
    original = getattr(Path, method)

    def operation(path, *args, **kwargs):
        if path == blocked:
            raise PermissionError("sibling denied")
        return original(path, *args, **kwargs)

    monkeypatch.setattr(Path, method, operation)
    if remove:
        source.unlink()
    else:
        source.write_bytes(b"new")
    ai.sync_global_instructions(other)
    target = staged(data_home).with_name("OTHER.md")
    if remove:
        assert not target.exists()
    else:
        assert target.read_bytes().endswith(b"\nnew")
    assert "sibling denied" in capsys.readouterr().err
    monkeypatch.undo()
    if not owned:
        assert blocked.read_bytes() == b"unrelated"


def test_legacy_adoption_survives_edits_and_source_recreation(homes, claude_cfg):
    source, data_home = homes
    target = staged(data_home)
    target.parent.mkdir(parents=True)
    legacy = target.with_name("LEGACY.md")
    source.write_bytes(b"old")
    legacy.write_bytes(
        f"<!-- generated by jailbee from {source} — edit that file on the host -->\nold".encode()
    )
    unknown = target.with_name("UNKNOWN.md")
    unknown.write_bytes(b"markerless pre-existing")
    ai.sync_global_instructions(claude_cfg)
    legacy.write_bytes(b"")
    source.unlink()
    ai.sync_global_instructions(claude_cfg)
    assert not legacy.exists()
    source.write_bytes(b"recreated")
    ai.sync_global_instructions(claude_cfg)
    assert legacy.read_bytes().endswith(b"\nrecreated")
    assert unknown.read_bytes() == b"markerless pre-existing"
    assert {p.name for p in target.parent.iterdir()} == {"CLAUDE.md", "LEGACY.md", "UNKNOWN.md"}


def test_registry_validates_names(homes, claude_cfg, capsys):
    import json

    source, data_home = homes
    source.write_bytes(b"old")
    ai.sync_global_instructions(claude_cfg)
    registry = data_home / "jailbee" / "agent-instructions-ownership" / "claude.json"
    outside = ai.staging_root() / "outside.md"
    outside.write_bytes(b"not ours")
    registry.write_text(
        json.dumps(["CLAUDE.md", "REMEMBERED.md", "../outside.md", "/tmp/x", "", ".", "..", 3])
    )
    source.write_bytes(b"new")
    ai.sync_global_instructions(claude_cfg)
    assert staged(data_home).with_name("REMEMBERED.md").read_bytes().endswith(b"\nnew")
    assert outside.read_bytes() == b"not ours"
    assert "invalid" in capsys.readouterr().err
    assert json.loads(registry.read_text()) == ["CLAUDE.md", "REMEMBERED.md"]


def test_corrupt_registry_retains_previous_copies(homes, claude_cfg, capsys):
    source, data_home = homes
    source.write_bytes(b"old")
    ai.sync_global_instructions(claude_cfg)
    registry = data_home / "jailbee" / "agent-instructions-ownership" / "claude.json"
    registry.write_bytes(b"broken json")
    source.unlink()
    ai.sync_global_instructions(claude_cfg)
    assert staged(data_home).read_bytes().endswith(b"\nold")
    assert registry.read_bytes() == b"broken json"
    assert "cannot update" in capsys.readouterr().err


def test_concurrent_sync_keeps_ownership_union(homes, claude_cfg):
    from concurrent.futures import ThreadPoolExecutor
    from threading import Barrier

    source, data_home = homes
    source.write_bytes(b"old")
    names = [f"REPO-{i}.md" for i in range(8)]
    configs = [
        with_agent(
            claude_cfg, "claude", global_instructions={"dir": "/etc/claude-code", "file": name}
        )
        for name in names
    ]
    barrier = Barrier(len(configs))

    def sync(cfg):
        barrier.wait(timeout=10)
        ai.sync_global_instructions(cfg)

    with ThreadPoolExecutor(max_workers=len(configs)) as executor:
        list(executor.map(sync, configs))
    for name in names:
        staged(data_home).with_name(name).write_bytes(b"marker gone")
    source.write_bytes(b"new")
    ai.sync_global_instructions(claude_cfg)
    for name in names:
        assert staged(data_home).with_name(name).read_bytes().endswith(b"\nnew")
