from pathlib import Path

import pytest

from jailbee import agent_instructions as ai
from tests.conftest import with_agent


@pytest.fixture
def homes(tmp_path, monkeypatch):
    cfg_home = tmp_path / "config"
    data_home = tmp_path / "data"
    monkeypatch.setenv("XDG_CONFIG_HOME", str(cfg_home))
    monkeypatch.setenv("XDG_DATA_HOME", str(data_home))
    (cfg_home / "jailbee").mkdir(parents=True)
    return cfg_home / "jailbee" / "AGENTS.md", data_home


@pytest.fixture
def claude_cfg(make_cfg, tmp_path):
    return make_cfg(tmp_path / "repo", agents={"claude": {"enabled": True}})


def staged(data_home: Path) -> Path:
    return data_home / "jailbee" / "agent-instructions" / "claude" / "CLAUDE.md"


def test_paths_follow_xdg(homes):
    source, data_home = homes
    assert ai.source_path() == source
    assert ai.staging_dir("claude") == data_home / "jailbee" / "agent-instructions" / "claude"


def test_instruction_agents_lists_enabled_claude(claude_cfg):
    [(name, gi)] = ai.instruction_agents(claude_cfg)
    assert (name, gi.dir, gi.file) == ("claude", "/etc/claude-code", "CLAUDE.md")


def test_instruction_agents_empty_when_opted_out(claude_cfg):
    claude_cfg._agent_instructions = False
    assert ai.instruction_agents(claude_cfg) == []


def test_instruction_agents_skips_disabled_agent(make_cfg, tmp_path):
    cfg = make_cfg(tmp_path / "repo", agents={"claude": {"enabled": False}})
    assert ai.instruction_agents(cfg) == []


def test_sync_copies_source_with_marker(homes, claude_cfg):
    source, data_home = homes
    source.write_bytes(b"Never use fable.\n")
    ai.sync_global_instructions(claude_cfg)
    content = staged(data_home).read_bytes()
    first, rest = content.split(b"\n", 1)
    assert first.decode() == (
        f"<!-- generated by jailbee from {source} — edit that file on the host -->"
    )
    assert rest == b"Never use fable.\n"


def test_sync_without_source_leaves_empty_dir(homes, claude_cfg):
    _, data_home = homes
    ai.sync_global_instructions(claude_cfg)
    assert staged(data_home).parent.is_dir()
    assert not staged(data_home).exists()


def test_sync_removes_staged_file_when_source_deleted(homes, claude_cfg):
    source, data_home = homes
    source.write_bytes(b"x")
    ai.sync_global_instructions(claude_cfg)
    source.unlink()
    ai.sync_global_instructions(claude_cfg)
    assert not staged(data_home).exists()
    assert staged(data_home).parent.is_dir()


def test_unchanged_content_is_not_rewritten(homes, claude_cfg):
    source, data_home = homes
    source.write_bytes(b"x")
    ai.sync_global_instructions(claude_cfg)
    before = staged(data_home).stat()
    ai.sync_global_instructions(claude_cfg)
    after = staged(data_home).stat()
    assert (before.st_ino, before.st_mtime_ns) == (after.st_ino, after.st_mtime_ns)


def test_changed_content_is_replaced_atomically(homes, claude_cfg):
    source, data_home = homes
    source.write_bytes(b"old")
    ai.sync_global_instructions(claude_cfg)
    before_ino = staged(data_home).stat().st_ino
    source.write_bytes(b"new")
    ai.sync_global_instructions(claude_cfg)
    assert staged(data_home).read_bytes().endswith(b"\nnew")
    assert staged(data_home).stat().st_ino != before_ino
    assert [p.name for p in staged(data_home).parent.iterdir()] == ["CLAUDE.md"]


def test_symlinked_source_stages_the_target(homes, claude_cfg, tmp_path):
    source, data_home = homes
    target = tmp_path / "dotfiles" / "AGENTS.md"
    target.parent.mkdir()
    target.write_bytes(b"from dotfiles")
    source.symlink_to(target)
    ai.sync_global_instructions(claude_cfg)
    assert staged(data_home).read_bytes().endswith(b"\nfrom dotfiles")


def test_bytes_are_staged_verbatim(homes, claude_cfg):
    source, data_home = homes
    payload = b"line one\r\nlatin-1: \xe4\xf6\r\n\x00end"
    source.write_bytes(payload)
    ai.sync_global_instructions(claude_cfg)
    assert staged(data_home).read_bytes().split(b"\n", 1)[1] == payload


def test_hand_edited_staged_file_is_restored(homes, claude_cfg):
    source, data_home = homes
    source.write_bytes(b"policy")
    ai.sync_global_instructions(claude_cfg)
    staged(data_home).write_bytes(b"tampered")
    ai.sync_global_instructions(claude_cfg)
    assert staged(data_home).read_bytes().endswith(b"\npolicy")


def test_unreadable_source_warns_and_keeps_previous(homes, claude_cfg, capsys):
    source, data_home = homes
    source.write_bytes(b"good")
    ai.sync_global_instructions(claude_cfg)
    source.unlink()
    source.mkdir()
    ai.sync_global_instructions(claude_cfg)
    assert staged(data_home).read_bytes().endswith(b"\ngood")
    assert "cannot read" in capsys.readouterr().out


def test_disabled_agent_in_this_repo_leaves_host_staging_alone(homes, make_cfg, tmp_path):
    source, data_home = homes
    source.write_bytes(b"policy")
    enabled = make_cfg(tmp_path / "b", agents={"claude": {"enabled": True}})
    ai.sync_global_instructions(enabled)
    source.unlink()
    disabled = make_cfg(tmp_path / "a", agents={"claude": {"enabled": False}})
    ai.sync_global_instructions(disabled)
    assert staged(data_home).read_bytes().endswith(b"\npolicy")


def test_write_failure_warns_not_raises(homes, claude_cfg, mocker, capsys):
    source, _ = homes
    source.write_bytes(b"x")
    mocker.patch("jailbee.agent_instructions.os.replace", side_effect=OSError("disk full"))
    ai.sync_global_instructions(claude_cfg)
    assert "disk full" in capsys.readouterr().out


def test_opted_out_sync_touches_nothing(homes, claude_cfg):
    source, data_home = homes
    source.write_bytes(b"x")
    claude_cfg._agent_instructions = False
    ai.sync_global_instructions(claude_cfg)
    assert not (data_home / "jailbee" / "agent-instructions").exists()


def test_missing_staging_dirs(homes, claude_cfg):
    _, data_home = homes
    assert ai.missing_staging_dirs(claude_cfg) == [
        data_home / "jailbee" / "agent-instructions" / "claude"
    ]
    ai.sync_global_instructions(claude_cfg)
    assert ai.missing_staging_dirs(claude_cfg) == []


def test_profile_devices_shape(homes, claude_cfg):
    _, data_home = homes
    assert ai.profile_devices(claude_cfg) == {
        "agent-instructions-claude": {
            "type": "disk",
            "source": str(data_home / "jailbee" / "agent-instructions" / "claude"),
            "path": "/etc/claude-code",
            "readonly": "true",
        }
    }


def test_profile_devices_expand_tilde(homes, make_cfg, tmp_path):
    cfg = with_agent(
        make_cfg(tmp_path / "repo"),
        "other",
        enabled=True,
        command="other",
        global_instructions={"dir": "~/.other-policy", "file": "AGENTS.md"},
    )
    devices = ai.profile_devices(cfg)
    assert devices["agent-instructions-other"]["path"] == "/home/dev/.other-policy"


def test_profile_devices_empty_when_opted_out(homes, claude_cfg):
    claude_cfg._agent_instructions = False
    assert ai.profile_devices(claude_cfg) == {}
