from pathlib import Path

import pytest

from jailbee import agent_instructions as ai
from tests.conftest import with_agent


@pytest.fixture
def homes(tmp_path, monkeypatch):
    home = tmp_path / "home"
    home.mkdir()
    monkeypatch.setenv("HOME", str(home))
    cfg_home = tmp_path / "config"
    data_home = tmp_path / "data"
    monkeypatch.setenv("XDG_CONFIG_HOME", str(cfg_home))
    monkeypatch.setenv("XDG_DATA_HOME", str(data_home))
    (cfg_home / "jailbee").mkdir(parents=True)
    return cfg_home / "jailbee" / "AGENTS.md", data_home


@pytest.fixture
def claude_cfg(make_cfg, tmp_path):
    return make_cfg(tmp_path / "repo", agents={"claude": {"enabled": True}})


def staged(data_home: Path) -> Path:
    return (
        data_home
        / "jailbee"
        / "agent-instructions"
        / "claude"
        / "by-file"
        / "CLAUDE.md"
        / "CLAUDE.md"
    )


def test_paths_follow_xdg(homes):
    source, data_home = homes
    assert ai.source_path() == source
    assert ai.staging_dir("claude", "CLAUDE.md") == staged(data_home).parent


def test_instruction_agents_lists_enabled_claude(claude_cfg):
    [(name, gi)] = ai.instruction_agents(claude_cfg)
    assert (name, gi.dir, gi.file) == ("claude", "/etc/claude-code", "CLAUDE.md")


def test_instruction_agents_empty_when_opted_out(claude_cfg):
    claude_cfg._agent_instructions = False
    assert ai.instruction_agents(claude_cfg) == []


def test_instruction_agents_skips_disabled_agent(make_cfg, tmp_path):
    cfg = make_cfg(tmp_path / "repo", agents={"claude": {"enabled": False}})
    assert ai.instruction_agents(cfg) == []


def test_sync_copies_source_with_marker(homes, claude_cfg):
    source, data_home = homes
    source.write_bytes(b"Never use fable.\n")
    ai.sync_global_instructions(claude_cfg)
    content = staged(data_home).read_bytes()
    first, rest = content.split(b"\n", 1)
    assert first.decode() == (
        f"<!-- generated by jailbee from {source} — edit that file on the host -->"
    )
    assert rest == b"Never use fable.\n"


def test_sync_without_source_leaves_empty_dir(homes, claude_cfg):
    _, data_home = homes
    ai.sync_global_instructions(claude_cfg)
    assert staged(data_home).parent.is_dir()
    assert not staged(data_home).exists()


def test_sync_removes_staged_file_when_source_deleted(homes, claude_cfg):
    source, data_home = homes
    source.write_bytes(b"x")
    ai.sync_global_instructions(claude_cfg)
    source.unlink()
    ai.sync_global_instructions(claude_cfg)
    assert not staged(data_home).exists()
    assert staged(data_home).parent.is_dir()


def test_unchanged_content_is_not_rewritten(homes, claude_cfg):
    source, data_home = homes
    source.write_bytes(b"x")
    ai.sync_global_instructions(claude_cfg)
    before = staged(data_home).stat()
    ai.sync_global_instructions(claude_cfg)
    after = staged(data_home).stat()
    assert (before.st_ino, before.st_mtime_ns) == (after.st_ino, after.st_mtime_ns)


def test_changed_content_is_replaced_atomically(homes, claude_cfg):
    source, data_home = homes
    source.write_bytes(b"old")
    ai.sync_global_instructions(claude_cfg)
    before_ino = staged(data_home).stat().st_ino
    source.write_bytes(b"new")
    ai.sync_global_instructions(claude_cfg)
    assert staged(data_home).read_bytes().endswith(b"\nnew")
    assert staged(data_home).stat().st_ino != before_ino
    assert [p.name for p in staged(data_home).parent.iterdir()] == ["CLAUDE.md"]


def test_symlinked_source_stages_the_target(homes, claude_cfg, tmp_path):
    source, data_home = homes
    target = tmp_path / "dotfiles" / "AGENTS.md"
    target.parent.mkdir()
    target.write_bytes(b"from dotfiles")
    source.symlink_to(target)
    ai.sync_global_instructions(claude_cfg)
    assert staged(data_home).read_bytes().endswith(b"\nfrom dotfiles")


def test_symlink_loop_warns_and_keeps_previous(homes, claude_cfg, capsys):
    source, data_home = homes
    source.write_bytes(b"good")
    ai.sync_global_instructions(claude_cfg)
    before = staged(data_home).read_bytes()
    source.unlink()
    source.symlink_to(source)
    ai.sync_global_instructions(claude_cfg)
    assert staged(data_home).read_bytes() == before
    output = capsys.readouterr()
    assert output.out == ""
    assert "cannot read" in output.err


def test_bytes_are_staged_verbatim(homes, claude_cfg):
    source, data_home = homes
    payload = b"line one\r\nlatin-1: \xe4\xf6\r\n\x00end"
    source.write_bytes(payload)
    ai.sync_global_instructions(claude_cfg)
    assert staged(data_home).read_bytes().split(b"\n", 1)[1] == payload


def test_hand_edited_staged_file_is_restored(homes, claude_cfg):
    source, data_home = homes
    source.write_bytes(b"policy")
    ai.sync_global_instructions(claude_cfg)
    staged(data_home).write_bytes(b"tampered")
    ai.sync_global_instructions(claude_cfg)
    assert staged(data_home).read_bytes().endswith(b"\npolicy")


def test_unreadable_source_warns_and_keeps_previous(homes, claude_cfg, capsys):
    source, data_home = homes
    source.write_bytes(b"good")
    ai.sync_global_instructions(claude_cfg)
    source.unlink()
    source.mkdir()
    ai.sync_global_instructions(claude_cfg)
    assert staged(data_home).read_bytes().endswith(b"\ngood")
    output = capsys.readouterr()
    assert output.out == ""
    assert "cannot read" in output.err


def test_disabled_agent_in_this_repo_leaves_host_staging_alone(homes, make_cfg, tmp_path):
    source, data_home = homes
    source.write_bytes(b"policy")
    enabled = make_cfg(tmp_path / "b", agents={"claude": {"enabled": True}})
    ai.sync_global_instructions(enabled)
    source.unlink()
    disabled = make_cfg(tmp_path / "a", agents={"claude": {"enabled": False}})
    ai.sync_global_instructions(disabled)
    assert staged(data_home).read_bytes().endswith(b"\npolicy")


def test_write_failure_warns_not_raises(homes, claude_cfg, mocker, capsys):
    source, _ = homes
    source.write_bytes(b"x")
    mocker.patch("jailbee.agent_instructions.os.replace", side_effect=OSError("disk [full]"))
    ai.sync_global_instructions(claude_cfg)
    output = capsys.readouterr()
    assert output.out == ""
    assert "disk [full]" in output.err


def test_opted_out_sync_touches_nothing(homes, claude_cfg):
    source, data_home = homes
    source.write_bytes(b"x")
    claude_cfg._agent_instructions = False
    ai.sync_global_instructions(claude_cfg)
    assert not (data_home / "jailbee" / "agent-instructions").exists()


def test_missing_staging_dirs(homes, claude_cfg):
    _, data_home = homes
    assert ai.missing_staging_dirs(claude_cfg) == [staged(data_home).parent]
    ai.sync_global_instructions(claude_cfg)
    assert ai.missing_staging_dirs(claude_cfg) == []


def test_profile_devices_shape(homes, claude_cfg):
    _, data_home = homes
    assert ai.profile_devices(claude_cfg) == {
        "agent-instructions-claude": {
            "type": "disk",
            "source": str(staged(data_home).parent),
            "path": "/etc/claude-code",
            "readonly": "true",
        }
    }


def test_profile_devices_expand_tilde(homes, make_cfg, tmp_path):
    cfg = with_agent(
        make_cfg(tmp_path / "repo"),
        "other",
        enabled=True,
        command="other",
        global_instructions={"dir": "~/.other-policy", "file": "AGENTS.md"},
    )
    devices = ai.profile_devices(cfg)
    assert devices["agent-instructions-other"]["path"] == "/home/dev/.other-policy"


def test_profile_devices_empty_when_opted_out(homes, claude_cfg):
    claude_cfg._agent_instructions = False
    assert ai.profile_devices(claude_cfg) == {}


@pytest.mark.parametrize(
    "destination",
    [
        "/etc/claude-code",
        "/etc",
        "/etc/claude-code/managed-settings.json",
        "/etc//claude-code/../claude-code/",
    ],
)
def test_instruction_mount_rejects_overlapping_host_policy(claude_cfg, destination):
    from jailbee.config import ConfigError, HostMount
    from jailbee.profiles import binds_profile_yaml

    cfg = claude_cfg.model_copy(
        update={"host_mounts": [HostMount(host="/policy", container=destination)]}
    )
    with pytest.raises(ConfigError, match=r"host.*policy.*agent_instructions: false"):
        binds_profile_yaml(cfg)
    cfg._agent_instructions = False
    assert "agent-instructions-claude" not in binds_profile_yaml(cfg)


def test_instruction_mount_rejects_normalized_shared_overlap(claude_cfg):
    from jailbee.config import ConfigError, SharedCache

    cfg = with_agent(
        claude_cfg,
        "other",
        enabled=True,
        command="other",
        global_instructions={"dir": "~/.policy", "file": "AGENTS.md"},
    )
    cfg = cfg.model_copy(
        update={
            "shared_caches": [
                SharedCache(
                    name="policy-state",
                    host_subpath="policy",
                    container_path="/home/dev//.policy/state",
                )
            ]
        }
    )
    with pytest.raises(ConfigError, match="shared-policy-state"):
        ai.profile_devices(cfg)


def test_instruction_mount_rejects_other_instruction_overlap(claude_cfg):
    from jailbee.config import ConfigError

    cfg = with_agent(
        claude_cfg,
        "other",
        enabled=True,
        command="other",
        global_instructions={"dir": "/etc/claude-code/nested", "file": "AGENTS.md"},
    )
    with pytest.raises(ConfigError, match=r"agent-instructions-other.*agent-instructions-claude"):
        ai.profile_devices(cfg)


def test_instruction_mount_accepts_segment_distinct_policy(claude_cfg):
    from jailbee.config import HostMount

    cfg = claude_cfg.model_copy(
        update={"host_mounts": [HostMount(host="/policy", container="/etc/claude-code-other")]}
    )
    assert "agent-instructions-claude" in ai.profile_devices(cfg)


def test_other_repos_file_name_never_reaches_this_repos_mount(homes, claude_cfg):
    source, data_home = homes
    source.write_bytes(b"policy")
    odd = with_agent(
        claude_cfg,
        "claude",
        global_instructions={"dir": "/etc/claude-code", "file": "managed-settings.json"},
    )
    ai.sync_global_instructions(odd)
    ai.sync_global_instructions(claude_cfg)
    assert [p.name for p in staged(data_home).parent.iterdir()] == ["CLAUDE.md"]
    assert ai.profile_devices(claude_cfg)["agent-instructions-claude"]["source"] == str(
        staged(data_home).parent
    )
    assert ai.staging_dir("claude", "managed-settings.json") != staged(data_home).parent


def test_reverted_file_name_stops_being_refreshed(homes, claude_cfg):
    source, data_home = homes
    source.write_bytes(b"old")
    renamed = with_agent(
        claude_cfg, "claude", global_instructions={"dir": "/etc/claude-code", "file": "NEW.md"}
    )
    ai.sync_global_instructions(renamed)
    stale = ai.staging_dir("claude", "NEW.md") / "NEW.md"
    source.write_bytes(b"new")
    ai.sync_global_instructions(claude_cfg)
    assert stale.read_bytes().endswith(b"\nold")
    assert staged(data_home).read_bytes().endswith(b"\nnew")


def test_sibling_agent_failure_does_not_block_other_agent(homes, claude_cfg, monkeypatch, capsys):
    source, _ = homes
    source.write_bytes(b"policy")
    cfg = with_agent(
        claude_cfg,
        "other",
        enabled=True,
        command="other",
        global_instructions={"dir": "/etc/other", "file": "AGENTS.md"},
    )
    blocked = ai.staging_dir("claude", "CLAUDE.md") / "CLAUDE.md"
    replace = ai.os.replace

    def fail_claude(src, dest):
        if dest == blocked:
            raise OSError("claude denied")
        return replace(src, dest)

    monkeypatch.setattr(ai.os, "replace", fail_claude)
    ai.sync_global_instructions(cfg)
    assert (ai.staging_dir("other", "AGENTS.md") / "AGENTS.md").read_bytes().endswith(b"policy")
    assert "claude denied" in capsys.readouterr().err
